apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-nyd5
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-bundle-tenant/appstudio/dc-metro-map-nyd5@sha256:238b2845e2c59281e51d67001b8c9091d3666ca837c6f98ec4c9eef1549a90ea
        name: my-nodejs
        resources: {}
status: {}
